### PR TITLE
Update to Blockly v10

### PR DESCRIPTION
**Pull request by ewpatton**

### CODE REVIEW

**Comment by ewpatton** [comment]
@mark-friedman We should decide whether bumping the Blockly major version implies a bump in the plugin major version. My guess is yes since the currently published version isn't forward compatible, making this a breaking change.

**Comment by mark-friedman** [comment]
> @mark-friedman We should decide whether bumping the Blockly major version implies a bump in the plugin major version. My guess is yes since the currently published version isn't forward compatible, making this a breaking change.

Yeah, I would definitely bump the major version number.  I probably should have done that for some of the other updates that I made to the plugin for new Blockly versions :-(

**Comment by mark-friedman** [comment]
@ewpatton, I think we've got a version now that works for both unit tests and via `run start`. Among other things, I had to change the Blockly imports back to `import Blockly from 'blockly'`  in order for the tests to run properly.  This presumably makes the built package larger again.  I'm sure that there is probably a way to be more specific with the imports in a way that makes it work for tests and when used with `run start` (and as an imported package), but the whole build/bundle/import process for JavaScript modules is still a bit of a mystery to me.

Just cc-ing @BeksOmega in case she's interested.

**Comment by ewpatton** [comment]
@mark-friedman We definitely need to fix this before going into production. Every extra 10 KB of code translates into $1.20 per month for us, at a minimum. So going from 71kb to 710kb means an additional $77/mo. There's also the cost to the end user to consider in terms of cost and load time.

**Comment by mark-friedman** [comment]
> @mark-friedman We definitely need to fix this before going into production. Every extra 10 KB of code translates into $1.20 per month for us, at a minimum. So going from 71kb to 710kb means an additional $77/mo. There's also the cost to the end user to consider in terms of cost and load time.

**Comment by mark-friedman** [comment]
> > @mark-friedman We definitely need to fix this before going into production.

Fair enough.  I'll look into it further.

**Review by mark-friedman — APPROVED** [review]

**Comment by mark-friedman** [comment]
Resolves #36

**Pull request merged**
